### ISSUE TITLE
Proposta de logo para PHP MT

### ISSUE THREAD

**Issue by enieber** [PHPMT/logo#1]
Quem tiver alguma proposta só mandar aqui nessa issue para decidirmos qual sera escolhida

**Comment by enieber** [comment]
O @webkennyroger fez o primeiro prototipo, só colocar a imagem aqui

**Comment by webkennyroger** [comment]
![logo](https://cloud.githubusercontent.com/assets/3782453/20643066/1f4ef080-b3fd-11e6-88aa-a301fd0b734b.jpg)

**Comment by enieber** [comment]
6

**Comment by enieber** [comment]
fechando essa issue até uma nova versão da logo
