### ISSUE TITLE
Nova proposta

### ISSUE THREAD

**Issue by f0ntana** [PHPMT/logo#2]
## Segue novas propostas favor votem:

Esqueçam as proporções serão melhoradas:

1 - ![screen shot 2016-12-14 at 23 04 50](https://cloud.githubusercontent.com/assets/6570783/21209444/0d445240-c253-11e6-9f68-a6d641b8986d.png)
2 -![screen shot 2016-12-14 at 23 08 20](https://cloud.githubusercontent.com/assets/6570783/21209445/0d4900f6-c253-11e6-8d9e-d43292115a80.png)
3- ![screen shot 2016-12-14 at 23 03 05](https://cloud.githubusercontent.com/assets/6570783/21209448/13473950-c253-11e6-9ad6-95eee5eeeab1.png)
4 - ![screen shot 2016-12-14 at 23 00 25](https://cloud.githubusercontent.com/assets/6570783/21209450/17b0065c-c253-11e6-9f68-9f8d77c6271f.png)
5 - ![screen shot 2016-12-14 at 22 56 24](https://cloud.githubusercontent.com/assets/6570783/21209453/1c1e2ebc-c253-11e6-9ff0-7bc4292ff6bd.png)
6- ![screen shot 2016-12-14 at 22 50 19](https://cloud.githubusercontent.com/assets/6570783/21209458/22c1b068-c253-11e6-85a7-41da7be0eaf7.png)
7- ![screen shot 2016-12-14 at 22 05 23](https://cloud.githubusercontent.com/assets/6570783/21209461/27f6f8ea-c253-11e6-948b-90a2c33ede9b.png)
8 - ![screen shot 2016-12-14 at 21 54 03](https://cloud.githubusercontent.com/assets/6570783/21209465/2f8edc26-c253-11e6-9592-872f2f9283b7.png)
9- ![screen shot 2016-12-14 at 21 47 03](https://cloud.githubusercontent.com/assets/6570783/21209469/33226830-c253-11e6-884d-500948edb709.png)

**Comment by enieber** [comment]
Achei legal a numero 2

**Comment by f0ntana** [comment]
More One:

![screen shot 2016-12-15 at 02 48 16](https://cloud.githubusercontent.com/assets/6570783/21213181/7f2bc884-c271-11e6-81f1-6ba9a673cd27.png)

**Comment by enieber** [comment]
bora usar essa, qualquer coisa nois muda depois...

**Comment by f0ntana** [comment]
Mas pelo menos poderia arrumar essa logo né? colocar alguma vetorizado
kkkkk não entendo nada disso

**Comment by enieber** [comment]
bora fechar essas issues, até a nova versão da logo...
